### ISSUE TITLE
Fix incorrect precommit indentation

### ISSUE THREAD

**Issue by matiasilva** [matiasilva/gsb-ticketing#19]
One of the formatting modules is not understanding that it's formatting a Django template and therefore indents things incorrectly and breaks the page. See the signup.html template.

**Comment by k12ish** [comment]
Ok that's kinda funny, I'll get that fixed asap. 

In the meantime, you can commit like this  to bypass `pre-commit`

```
git commit --no-verify
```

**Comment by matiasilva** [comment]
I've noticed your fix, but is there any way to tell it to recognize it's a Django template and apply the required formatting? The Django templating language is pretty well known, so I'd be surprised if no option like that exists.

**Comment by k12ish** [comment]
Only one well known formatters have a Django compatibility, and it doesn't have `pre-commit` support.

I did find this: https://github.com/rtts/djhtml

I'll write a commit, you decide if it's worth keeping

**Comment by matiasilva** [comment]
Looks good! Thanks so much for this.
